version: "3"

vars:
  DSN: "{{.DB_CONNECTION}}://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode=disable"

dotenv:
  - ".env"

tasks:
  build:
    desc: build the api and worker binaries
    cmds:
      - go build -o bin/api cmd/api/main.go
      - go build -o bin/worker cmd/worker/main.go

  clean:
    desc: remove built binaries
    cmds:
      - rm -rf bin/
  dev:
    desc: run both api and worker in parallel
    deps: [build, db:up, mq:up]
    cmds:
      - ./bin/api
      - ./bin/worker
    parallel: true

  install:
    cmd: go mod tidy

  test:
    cmd: go test ./... -v
  test:repository:
    cmd: go test ./tests/repository -v
  test:service:
    cmd: go test ./tests/services -v

  db:up:
    cmd: docker-compose up db -d
  db:down:
    cmd: docker-compose down db -v
  db:cli:
    cmd: docker exec -it db sh -c "psql -U {{.DB_USER}} -d {{.DB_NAME}}"
    requires:
      vars:
        - DB_USER
        - DB_NAME
  db:studio:
    cmd: sql-studio postgres {{.DSN}}
  migrate:up:
    cmd: migrate -path ./internal/repository/migrations -database {{.DSN}} -verbose up {{.CLI_ARGS}}
    requires:
      vars:
        - DSN
  migrate:down:
    cmd: migrate -path ./internal/repository/migrations -database {{.DSN}} --verbose down
    requires:
      vars:
        - DSN

  mq:up:
    cmd: docker-compose up rabbitmq -d
  mq:down:
    cmd: docker-compose down rabbitmq -v


  api:up:
    cmd: docker-compose up api
  api:down:
    cmd: docker-compose down api -v

  worker:up:
    cmd: docker-compose up worker
  worker:down:
    cmd: docker-compose down worker -v
  
  app:
    cmd: docker-compose up --build

  test:load:
    desc: run load tests using k6 in docker
    cmd: docker run --rm -i grafana/k6 run - <tests/load_test.js
